name: Pickle Test

on: [push, pull_request]

jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run generate
      run: |
        python generate_data.py ${{ matrix.python-version }} ${{ matrix.os }}

    - name: Upload generated data
      uses: actions/upload-artifact@v3
      with:
        name: generated-data-${{ matrix.os }}-${{ matrix.python-version }}
        path: pkl_files/

    compare:
      runs-on: ubuntu-latest
      needs: generate
      steps:
      - uses: actions/checkout@v2

      - name: Download generated data
        uses: actions/download-artifact@v3
        with:
          name: generated-data-${{ matrix.os }}-${{ matrix.python-version }}

      - name: compare generated files
        run: |
          python compare.py
          